spring:
  application:
    name: Wantedlicense
  datasource:
    url: jdbc:mysql://localhost:3306/license_db2?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # update para dev, validate ou none para prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      indent-output: true
server:
  port: 8080


